//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alluberes.hosteleria.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        public int IdHabitacion { get; set; }
        public string Codigo { get; set; }
    }
}
