//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alluberes.hosteleria.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int ReservaId { get; set; }
        public int UsuarioId { get; set; }
        public int OfertaId { get; set; }
        public System.DateTime FechaReserva { get; set; }
        public string Comentario { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Oferta Oferta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
