//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alluberes.hosteleria.webUILogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int ComentarioId { get; set; }
        public Nullable<int> OfertaId { get; set; }
        public string Nota { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Fecha_comentario { get; set; }
    
        public virtual Oferta Oferta { get; set; }
    }
}
